### ISSUE TITLE
Nonfunctional in Private Browsing Mode

### ISSUE THREAD

**Issue by BenWestcott** [jake-cryptic/AbsoluteDoubleTrace#30] opened 2019-08-30 23:35 UTC
When running in private browsing mode (Firefox), the user interface can be opened, but it does not function. "home" under the smaller icon menu remains empty. The "report" and "whitelist" tabs load the proper content, including the URL of the current page, but the buttons are nonfunctional.
If I open the dashboard, everything is "loading" or "checking status", and again while I can open the different tabs, the buttons (e.x. enable/disable a thing) do not work, except for the pop-up dialogs under "whitelist".
Desktop is currently on v2.3.5. The exact same behavior can be replicated on the Fennec F-Droid version of Firefox, with trace v2.3.6.

I'm guessing Trace stores some data in fixed locations and running two instances simultaneously (private and not private) clashes?

**Comment by jake-cryptic** [comment] 2019-08-31 16:46
Hi,

I've been able to recreate the issue and will be investigating the cause of it immediately.

I shall update this thread with my progress.

Thanks

**Comment by jake-cryptic** [comment] 2019-08-31 17:13
Unfortunately this issue cannot be easily fixed without re-writing large portions of the options page code...

The extension will function in private mode however communication with the background script is not possible due to Firefox's implementation, as detailed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1329304

Modifying settings for the extension will have to be done in a non-private window. I will add more information into Trace in the next update detailing this.

Once again, thank you for raising the issue.

**Closed by jake-cryptic** 2019-08-31 17:13 UTC
Labels: bug

**Comment by jake-cryptic** [comment] 2019-09-03 23:12
Just to clarify the actions that will be taken as a result of this issue...

The options page in a future version will alert the user that an error has occurred and why this is the case.
As well as this, the new settings page that is being developed will use a different method of communication with the background script so that this error no longer occurs.

I cannot fix the current options page as that would mean re-writing lots of code just for this one specific case.
