### ISSUE TITLE
Google image doesn't showup since 2.3

### ISSUE THREAD

**Issue by defcon44** [jake-cryptic/AbsoluteDoubleTrace#20] opened 2019-07-19 21:44 UTC
**Describe the bug**
Hello, Since the 2.3 update I saw that the google image didn't showup when you click on them so I deactivated every extension I have and the problem appears when I activated Trace. Hope you can fix this bugs, thanks !

**To Reproduce**
1. Go to 'Google'
2. Made a random search
3. Go to Google image
4. Normally, some image don't wshow up, only few of them 

**Screenshots**
https://gyazo.com/d13be87ab5d764822caa36eb0a771f48

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version 75.0.3770.142

**Comment by jake-cryptic** [comment] 2019-07-22 18:20
Hi,

I've identified the issue as being caused by the getClientRects protection. This was updated in 2.3 and so I will have a look at fixing it in 2.3.2

This thread will be updated once the issue is fixed.

Thanks for bringing this to my attention

**Comment by defcon44** [comment] 2019-07-22 18:21
Hi, 
Great ! My pleasure to help :)

**Comment by jake-cryptic** [comment] 2019-07-23 12:13
I can confirm the issue is caused by the new getBoundingClientRects code, specifically this part:

https://github.com/jake-cryptic/AbsoluteDoubleTrace/blob/7c5cc4bf4d953ee7b3e08384d35f3ae90f596c59/MyTrace/js/contentscript/page.js#L604

However removing this would remove the protection so I am trying to figure out why this causes google images to break.

**Comment by jake-cryptic** [comment] 2019-08-01 11:45
Fixed in 2.3.2

**Closed by jake-cryptic** 2019-08-01 11:45 UTC
Labels: bug

**Comment by defcon44** [comment] 2019-08-04 21:29
Great thanks ! 
Sorry for the late reply.
