### ISSUE TITLE
AudioContex Fingerprint Protection dosent work

### ISSUE THREAD

**Issue by perezpermrs201** [jake-cryptic/AbsoluteDoubleTrace#24] opened 2019-07-28 07:02 UTC
AudioContex Protection dosent work on Chrome Browser,

w7 x64, Chrome 74, 75, 76

AudioContext Fingerprint Test Page:
https://audiofingerprint.openwpm.com/

**Comment by jake-cryptic** [comment] 2019-07-30 00:08
Hi,

I was unable to recreate the issue you're describing. Audio fingerprinting protection will modify your fingerprint not stop the site from viewing it.

You will know the protection is working by completing the following:
Load the test page, check the "Fingerprint using DynamicsCompressor (hash of full buffer):" value
Reload the page and if the value has changed then your fingerprint is not unique meaning you can't be tracked.

If it stays the same however then there is an issue which I shall have to look into :)

Thanks

**Comment by jake-cryptic** [comment] 2019-09-03 10:09
I think this issue may have been caused by a bug that was fixed in 2.3.5, I will be closing the issue now however if the issue persists please reopen it.

**Closed by jake-cryptic** 2019-09-03 10:09 UTC
Labels: question
